apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test01
  namespace: default     # 필요! ArgoCD가 네임스페이스 알 수 있게
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: web-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80   # 웹서비스 포트 명시

